@startuml
interface "ISQLiteParserVisitor`1"<Result> {
    VisitParse(context:SQLiteParser.ParseContext) : Result
    VisitSql_stmt_list(context:SQLiteParser.Sql_stmt_listContext) : Result
    VisitSql_stmt(context:SQLiteParser.Sql_stmtContext) : Result
    VisitAlter_table_stmt(context:SQLiteParser.Alter_table_stmtContext) : Result
    VisitAnalyze_stmt(context:SQLiteParser.Analyze_stmtContext) : Result
    VisitAttach_stmt(context:SQLiteParser.Attach_stmtContext) : Result
    VisitBegin_stmt(context:SQLiteParser.Begin_stmtContext) : Result
    VisitCommit_stmt(context:SQLiteParser.Commit_stmtContext) : Result
    VisitRollback_stmt(context:SQLiteParser.Rollback_stmtContext) : Result
    VisitSavepoint_stmt(context:SQLiteParser.Savepoint_stmtContext) : Result
    VisitRelease_stmt(context:SQLiteParser.Release_stmtContext) : Result
    VisitCreate_index_stmt(context:SQLiteParser.Create_index_stmtContext) : Result
    VisitIndexed_column(context:SQLiteParser.Indexed_columnContext) : Result
    VisitCreate_table_stmt(context:SQLiteParser.Create_table_stmtContext) : Result
    VisitColumn_def(context:SQLiteParser.Column_defContext) : Result
    VisitType_name(context:SQLiteParser.Type_nameContext) : Result
    VisitColumn_constraint(context:SQLiteParser.Column_constraintContext) : Result
    VisitSigned_number(context:SQLiteParser.Signed_numberContext) : Result
    VisitTable_constraint(context:SQLiteParser.Table_constraintContext) : Result
    VisitForeign_key_clause(context:SQLiteParser.Foreign_key_clauseContext) : Result
    VisitConflict_clause(context:SQLiteParser.Conflict_clauseContext) : Result
    VisitCreate_trigger_stmt(context:SQLiteParser.Create_trigger_stmtContext) : Result
    VisitCreate_view_stmt(context:SQLiteParser.Create_view_stmtContext) : Result
    VisitCreate_virtual_table_stmt(context:SQLiteParser.Create_virtual_table_stmtContext) : Result
    VisitWith_clause(context:SQLiteParser.With_clauseContext) : Result
    VisitCte_table_name(context:SQLiteParser.Cte_table_nameContext) : Result
    VisitRecursive_cte(context:SQLiteParser.Recursive_cteContext) : Result
    VisitCommon_table_expression(context:SQLiteParser.Common_table_expressionContext) : Result
    VisitDelete_stmt(context:SQLiteParser.Delete_stmtContext) : Result
    VisitDelete_stmt_limited(context:SQLiteParser.Delete_stmt_limitedContext) : Result
    VisitDetach_stmt(context:SQLiteParser.Detach_stmtContext) : Result
    VisitDrop_stmt(context:SQLiteParser.Drop_stmtContext) : Result
    VisitExpr(context:SQLiteParser.ExprContext) : Result
    VisitRaise_function(context:SQLiteParser.Raise_functionContext) : Result
    VisitLiteral_value(context:SQLiteParser.Literal_valueContext) : Result
    VisitColumns_clause(context:SQLiteParser.Columns_clauseContext) : Result
    VisitInsert_stmt(context:SQLiteParser.Insert_stmtContext) : Result
    VisitReturning_clause(context:SQLiteParser.Returning_clauseContext) : Result
    VisitUpsert_clause(context:SQLiteParser.Upsert_clauseContext) : Result
    VisitPragma_stmt(context:SQLiteParser.Pragma_stmtContext) : Result
    VisitPragma_value(context:SQLiteParser.Pragma_valueContext) : Result
    VisitReindex_stmt(context:SQLiteParser.Reindex_stmtContext) : Result
    VisitSelect_stmt(context:SQLiteParser.Select_stmtContext) : Result
    VisitJoin_stmt(context:SQLiteParser.Join_stmtContext) : Result
    VisitJoin_clause(context:SQLiteParser.Join_clauseContext) : Result
    VisitWhere_clause(context:SQLiteParser.Where_clauseContext) : Result
    VisitGroup_by_clause(context:SQLiteParser.Group_by_clauseContext) : Result
    VisitHaving_clause(context:SQLiteParser.Having_clauseContext) : Result
    VisitValues_clause(context:SQLiteParser.Values_clauseContext) : Result
    VisitValues_stmt(context:SQLiteParser.Values_stmtContext) : Result
    VisitFrom_clause(context:SQLiteParser.From_clauseContext) : Result
    VisitWindow_clause(context:SQLiteParser.Window_clauseContext) : Result
    VisitSelect_core(context:SQLiteParser.Select_coreContext) : Result
    VisitFactored_select_stmt(context:SQLiteParser.Factored_select_stmtContext) : Result
    VisitSimple_select_stmt(context:SQLiteParser.Simple_select_stmtContext) : Result
    VisitCompound_select_stmt(context:SQLiteParser.Compound_select_stmtContext) : Result
    VisitTable_or_subquery(context:SQLiteParser.Table_or_subqueryContext) : Result
    VisitResult_column(context:SQLiteParser.Result_columnContext) : Result
    VisitJoin_operator(context:SQLiteParser.Join_operatorContext) : Result
    VisitJoin_constraint(context:SQLiteParser.Join_constraintContext) : Result
    VisitCompound_operator(context:SQLiteParser.Compound_operatorContext) : Result
    VisitSet_clause(context:SQLiteParser.Set_clauseContext) : Result
    VisitSet_stmt(context:SQLiteParser.Set_stmtContext) : Result
    VisitUpdate_stmt(context:SQLiteParser.Update_stmtContext) : Result
    VisitColumn_name_list(context:SQLiteParser.Column_name_listContext) : Result
    VisitUpdate_stmt_limited(context:SQLiteParser.Update_stmt_limitedContext) : Result
    VisitQualified_table_name(context:SQLiteParser.Qualified_table_nameContext) : Result
    VisitVacuum_stmt(context:SQLiteParser.Vacuum_stmtContext) : Result
    VisitFilter_clause(context:SQLiteParser.Filter_clauseContext) : Result
    VisitWindow_defn(context:SQLiteParser.Window_defnContext) : Result
    VisitOver_clause(context:SQLiteParser.Over_clauseContext) : Result
    VisitFrame_spec(context:SQLiteParser.Frame_specContext) : Result
    VisitFrame_clause(context:SQLiteParser.Frame_clauseContext) : Result
    VisitSimple_function_invocation(context:SQLiteParser.Simple_function_invocationContext) : Result
    VisitAggregate_function_invocation(context:SQLiteParser.Aggregate_function_invocationContext) : Result
    VisitWindow_function_invocation(context:SQLiteParser.Window_function_invocationContext) : Result
    VisitCommon_table_stmt(context:SQLiteParser.Common_table_stmtContext) : Result
    VisitOrder_by_clause(context:SQLiteParser.Order_by_clauseContext) : Result
    VisitLimit_clause(context:SQLiteParser.Limit_clauseContext) : Result
    VisitOffset_clause(context:SQLiteParser.Offset_clauseContext) : Result
    VisitOrdering_term(context:SQLiteParser.Ordering_termContext) : Result
    VisitAsc_desc(context:SQLiteParser.Asc_descContext) : Result
    VisitFrame_left(context:SQLiteParser.Frame_leftContext) : Result
    VisitFrame_right(context:SQLiteParser.Frame_rightContext) : Result
    VisitFrame_single(context:SQLiteParser.Frame_singleContext) : Result
    VisitWindow_function(context:SQLiteParser.Window_functionContext) : Result
    VisitOffset(context:SQLiteParser.OffsetContext) : Result
    VisitDefault_value(context:SQLiteParser.Default_valueContext) : Result
    VisitPartition_by(context:SQLiteParser.Partition_byContext) : Result
    VisitOrder_by_expr(context:SQLiteParser.Order_by_exprContext) : Result
    VisitOrder_by_expr_asc_desc(context:SQLiteParser.Order_by_expr_asc_descContext) : Result
    VisitExpr_asc_desc(context:SQLiteParser.Expr_asc_descContext) : Result
    VisitInitial_select(context:SQLiteParser.Initial_selectContext) : Result
    VisitRecursive_select(context:SQLiteParser.Recursive_selectContext) : Result
    VisitUnary_operator(context:SQLiteParser.Unary_operatorContext) : Result
    VisitError_message(context:SQLiteParser.Error_messageContext) : Result
    VisitModule_argument(context:SQLiteParser.Module_argumentContext) : Result
    VisitColumn_alias(context:SQLiteParser.Column_aliasContext) : Result
    VisitKeyword(context:SQLiteParser.KeywordContext) : Result
    VisitName(context:SQLiteParser.NameContext) : Result
    VisitFunction_name(context:SQLiteParser.Function_nameContext) : Result
    VisitSchema_name(context:SQLiteParser.Schema_nameContext) : Result
    VisitTable_name(context:SQLiteParser.Table_nameContext) : Result
    VisitTable_or_index_name(context:SQLiteParser.Table_or_index_nameContext) : Result
    VisitColumn_name(context:SQLiteParser.Column_nameContext) : Result
    VisitCollation_name(context:SQLiteParser.Collation_nameContext) : Result
    VisitForeign_table(context:SQLiteParser.Foreign_tableContext) : Result
    VisitIndex_name(context:SQLiteParser.Index_nameContext) : Result
    VisitTrigger_name(context:SQLiteParser.Trigger_nameContext) : Result
    VisitView_name(context:SQLiteParser.View_nameContext) : Result
    VisitModule_name(context:SQLiteParser.Module_nameContext) : Result
    VisitPragma_name(context:SQLiteParser.Pragma_nameContext) : Result
    VisitSavepoint_name(context:SQLiteParser.Savepoint_nameContext) : Result
    VisitTable_alias(context:SQLiteParser.Table_aliasContext) : Result
    VisitTransaction_name(context:SQLiteParser.Transaction_nameContext) : Result
    VisitWindow_name(context:SQLiteParser.Window_nameContext) : Result
    VisitAlias(context:SQLiteParser.AliasContext) : Result
    VisitFilename(context:SQLiteParser.FilenameContext) : Result
    VisitBase_window_name(context:SQLiteParser.Base_window_nameContext) : Result
    VisitSimple_func(context:SQLiteParser.Simple_funcContext) : Result
    VisitAggregate_func(context:SQLiteParser.Aggregate_funcContext) : Result
    VisitTable_function_name(context:SQLiteParser.Table_function_nameContext) : Result
    VisitAny_name(context:SQLiteParser.Any_nameContext) : Result
}
class "IParseTreeVisitor`1"<T> {
}
"IParseTreeVisitor`1" "<Result>" <|-- "ISQLiteParserVisitor`1"
@enduml
