@startuml
class SQLiteParserBaseListener <<partial>> {
    + <<virtual>> EnterParse(context:SQLiteParser.ParseContext) : void
    + <<virtual>> ExitParse(context:SQLiteParser.ParseContext) : void
    + <<virtual>> EnterSql_stmt_list(context:SQLiteParser.Sql_stmt_listContext) : void
    + <<virtual>> ExitSql_stmt_list(context:SQLiteParser.Sql_stmt_listContext) : void
    + <<virtual>> EnterSql_stmt(context:SQLiteParser.Sql_stmtContext) : void
    + <<virtual>> ExitSql_stmt(context:SQLiteParser.Sql_stmtContext) : void
    + <<virtual>> EnterAlter_table_stmt(context:SQLiteParser.Alter_table_stmtContext) : void
    + <<virtual>> ExitAlter_table_stmt(context:SQLiteParser.Alter_table_stmtContext) : void
    + <<virtual>> EnterAnalyze_stmt(context:SQLiteParser.Analyze_stmtContext) : void
    + <<virtual>> ExitAnalyze_stmt(context:SQLiteParser.Analyze_stmtContext) : void
    + <<virtual>> EnterAttach_stmt(context:SQLiteParser.Attach_stmtContext) : void
    + <<virtual>> ExitAttach_stmt(context:SQLiteParser.Attach_stmtContext) : void
    + <<virtual>> EnterBegin_stmt(context:SQLiteParser.Begin_stmtContext) : void
    + <<virtual>> ExitBegin_stmt(context:SQLiteParser.Begin_stmtContext) : void
    + <<virtual>> EnterCommit_stmt(context:SQLiteParser.Commit_stmtContext) : void
    + <<virtual>> ExitCommit_stmt(context:SQLiteParser.Commit_stmtContext) : void
    + <<virtual>> EnterRollback_stmt(context:SQLiteParser.Rollback_stmtContext) : void
    + <<virtual>> ExitRollback_stmt(context:SQLiteParser.Rollback_stmtContext) : void
    + <<virtual>> EnterSavepoint_stmt(context:SQLiteParser.Savepoint_stmtContext) : void
    + <<virtual>> ExitSavepoint_stmt(context:SQLiteParser.Savepoint_stmtContext) : void
    + <<virtual>> EnterRelease_stmt(context:SQLiteParser.Release_stmtContext) : void
    + <<virtual>> ExitRelease_stmt(context:SQLiteParser.Release_stmtContext) : void
    + <<virtual>> EnterCreate_index_stmt(context:SQLiteParser.Create_index_stmtContext) : void
    + <<virtual>> ExitCreate_index_stmt(context:SQLiteParser.Create_index_stmtContext) : void
    + <<virtual>> EnterIndexed_column(context:SQLiteParser.Indexed_columnContext) : void
    + <<virtual>> ExitIndexed_column(context:SQLiteParser.Indexed_columnContext) : void
    + <<virtual>> EnterCreate_table_stmt(context:SQLiteParser.Create_table_stmtContext) : void
    + <<virtual>> ExitCreate_table_stmt(context:SQLiteParser.Create_table_stmtContext) : void
    + <<virtual>> EnterColumn_def(context:SQLiteParser.Column_defContext) : void
    + <<virtual>> ExitColumn_def(context:SQLiteParser.Column_defContext) : void
    + <<virtual>> EnterType_name(context:SQLiteParser.Type_nameContext) : void
    + <<virtual>> ExitType_name(context:SQLiteParser.Type_nameContext) : void
    + <<virtual>> EnterColumn_constraint(context:SQLiteParser.Column_constraintContext) : void
    + <<virtual>> ExitColumn_constraint(context:SQLiteParser.Column_constraintContext) : void
    + <<virtual>> EnterSigned_number(context:SQLiteParser.Signed_numberContext) : void
    + <<virtual>> ExitSigned_number(context:SQLiteParser.Signed_numberContext) : void
    + <<virtual>> EnterTable_constraint(context:SQLiteParser.Table_constraintContext) : void
    + <<virtual>> ExitTable_constraint(context:SQLiteParser.Table_constraintContext) : void
    + <<virtual>> EnterForeign_key_clause(context:SQLiteParser.Foreign_key_clauseContext) : void
    + <<virtual>> ExitForeign_key_clause(context:SQLiteParser.Foreign_key_clauseContext) : void
    + <<virtual>> EnterConflict_clause(context:SQLiteParser.Conflict_clauseContext) : void
    + <<virtual>> ExitConflict_clause(context:SQLiteParser.Conflict_clauseContext) : void
    + <<virtual>> EnterCreate_trigger_stmt(context:SQLiteParser.Create_trigger_stmtContext) : void
    + <<virtual>> ExitCreate_trigger_stmt(context:SQLiteParser.Create_trigger_stmtContext) : void
    + <<virtual>> EnterCreate_view_stmt(context:SQLiteParser.Create_view_stmtContext) : void
    + <<virtual>> ExitCreate_view_stmt(context:SQLiteParser.Create_view_stmtContext) : void
    + <<virtual>> EnterCreate_virtual_table_stmt(context:SQLiteParser.Create_virtual_table_stmtContext) : void
    + <<virtual>> ExitCreate_virtual_table_stmt(context:SQLiteParser.Create_virtual_table_stmtContext) : void
    + <<virtual>> EnterWith_clause(context:SQLiteParser.With_clauseContext) : void
    + <<virtual>> ExitWith_clause(context:SQLiteParser.With_clauseContext) : void
    + <<virtual>> EnterCte_table_name(context:SQLiteParser.Cte_table_nameContext) : void
    + <<virtual>> ExitCte_table_name(context:SQLiteParser.Cte_table_nameContext) : void
    + <<virtual>> EnterRecursive_cte(context:SQLiteParser.Recursive_cteContext) : void
    + <<virtual>> ExitRecursive_cte(context:SQLiteParser.Recursive_cteContext) : void
    + <<virtual>> EnterCommon_table_expression(context:SQLiteParser.Common_table_expressionContext) : void
    + <<virtual>> ExitCommon_table_expression(context:SQLiteParser.Common_table_expressionContext) : void
    + <<virtual>> EnterDelete_stmt(context:SQLiteParser.Delete_stmtContext) : void
    + <<virtual>> ExitDelete_stmt(context:SQLiteParser.Delete_stmtContext) : void
    + <<virtual>> EnterDelete_stmt_limited(context:SQLiteParser.Delete_stmt_limitedContext) : void
    + <<virtual>> ExitDelete_stmt_limited(context:SQLiteParser.Delete_stmt_limitedContext) : void
    + <<virtual>> EnterDetach_stmt(context:SQLiteParser.Detach_stmtContext) : void
    + <<virtual>> ExitDetach_stmt(context:SQLiteParser.Detach_stmtContext) : void
    + <<virtual>> EnterDrop_stmt(context:SQLiteParser.Drop_stmtContext) : void
    + <<virtual>> ExitDrop_stmt(context:SQLiteParser.Drop_stmtContext) : void
    + <<virtual>> EnterExpr(context:SQLiteParser.ExprContext) : void
    + <<virtual>> ExitExpr(context:SQLiteParser.ExprContext) : void
    + <<virtual>> EnterRaise_function(context:SQLiteParser.Raise_functionContext) : void
    + <<virtual>> ExitRaise_function(context:SQLiteParser.Raise_functionContext) : void
    + <<virtual>> EnterLiteral_value(context:SQLiteParser.Literal_valueContext) : void
    + <<virtual>> ExitLiteral_value(context:SQLiteParser.Literal_valueContext) : void
    + <<virtual>> EnterColumns_clause(context:SQLiteParser.Columns_clauseContext) : void
    + <<virtual>> ExitColumns_clause(context:SQLiteParser.Columns_clauseContext) : void
    + <<virtual>> EnterInsert_stmt(context:SQLiteParser.Insert_stmtContext) : void
    + <<virtual>> ExitInsert_stmt(context:SQLiteParser.Insert_stmtContext) : void
    + <<virtual>> EnterReturning_clause(context:SQLiteParser.Returning_clauseContext) : void
    + <<virtual>> ExitReturning_clause(context:SQLiteParser.Returning_clauseContext) : void
    + <<virtual>> EnterUpsert_clause(context:SQLiteParser.Upsert_clauseContext) : void
    + <<virtual>> ExitUpsert_clause(context:SQLiteParser.Upsert_clauseContext) : void
    + <<virtual>> EnterPragma_stmt(context:SQLiteParser.Pragma_stmtContext) : void
    + <<virtual>> ExitPragma_stmt(context:SQLiteParser.Pragma_stmtContext) : void
    + <<virtual>> EnterPragma_value(context:SQLiteParser.Pragma_valueContext) : void
    + <<virtual>> ExitPragma_value(context:SQLiteParser.Pragma_valueContext) : void
    + <<virtual>> EnterReindex_stmt(context:SQLiteParser.Reindex_stmtContext) : void
    + <<virtual>> ExitReindex_stmt(context:SQLiteParser.Reindex_stmtContext) : void
    + <<virtual>> EnterSelect_stmt(context:SQLiteParser.Select_stmtContext) : void
    + <<virtual>> ExitSelect_stmt(context:SQLiteParser.Select_stmtContext) : void
    + <<virtual>> EnterJoin_stmt(context:SQLiteParser.Join_stmtContext) : void
    + <<virtual>> ExitJoin_stmt(context:SQLiteParser.Join_stmtContext) : void
    + <<virtual>> EnterJoin_clause(context:SQLiteParser.Join_clauseContext) : void
    + <<virtual>> ExitJoin_clause(context:SQLiteParser.Join_clauseContext) : void
    + <<virtual>> EnterWhere_clause(context:SQLiteParser.Where_clauseContext) : void
    + <<virtual>> ExitWhere_clause(context:SQLiteParser.Where_clauseContext) : void
    + <<virtual>> EnterGroup_by_clause(context:SQLiteParser.Group_by_clauseContext) : void
    + <<virtual>> ExitGroup_by_clause(context:SQLiteParser.Group_by_clauseContext) : void
    + <<virtual>> EnterHaving_clause(context:SQLiteParser.Having_clauseContext) : void
    + <<virtual>> ExitHaving_clause(context:SQLiteParser.Having_clauseContext) : void
    + <<virtual>> EnterValues_clause(context:SQLiteParser.Values_clauseContext) : void
    + <<virtual>> ExitValues_clause(context:SQLiteParser.Values_clauseContext) : void
    + <<virtual>> EnterValues_stmt(context:SQLiteParser.Values_stmtContext) : void
    + <<virtual>> ExitValues_stmt(context:SQLiteParser.Values_stmtContext) : void
    + <<virtual>> EnterFrom_clause(context:SQLiteParser.From_clauseContext) : void
    + <<virtual>> ExitFrom_clause(context:SQLiteParser.From_clauseContext) : void
    + <<virtual>> EnterWindow_clause(context:SQLiteParser.Window_clauseContext) : void
    + <<virtual>> ExitWindow_clause(context:SQLiteParser.Window_clauseContext) : void
    + <<virtual>> EnterSelect_core(context:SQLiteParser.Select_coreContext) : void
    + <<virtual>> ExitSelect_core(context:SQLiteParser.Select_coreContext) : void
    + <<virtual>> EnterFactored_select_stmt(context:SQLiteParser.Factored_select_stmtContext) : void
    + <<virtual>> ExitFactored_select_stmt(context:SQLiteParser.Factored_select_stmtContext) : void
    + <<virtual>> EnterSimple_select_stmt(context:SQLiteParser.Simple_select_stmtContext) : void
    + <<virtual>> ExitSimple_select_stmt(context:SQLiteParser.Simple_select_stmtContext) : void
    + <<virtual>> EnterCompound_select_stmt(context:SQLiteParser.Compound_select_stmtContext) : void
    + <<virtual>> ExitCompound_select_stmt(context:SQLiteParser.Compound_select_stmtContext) : void
    + <<virtual>> EnterTable_or_subquery(context:SQLiteParser.Table_or_subqueryContext) : void
    + <<virtual>> ExitTable_or_subquery(context:SQLiteParser.Table_or_subqueryContext) : void
    + <<virtual>> EnterResult_column(context:SQLiteParser.Result_columnContext) : void
    + <<virtual>> ExitResult_column(context:SQLiteParser.Result_columnContext) : void
    + <<virtual>> EnterJoin_operator(context:SQLiteParser.Join_operatorContext) : void
    + <<virtual>> ExitJoin_operator(context:SQLiteParser.Join_operatorContext) : void
    + <<virtual>> EnterJoin_constraint(context:SQLiteParser.Join_constraintContext) : void
    + <<virtual>> ExitJoin_constraint(context:SQLiteParser.Join_constraintContext) : void
    + <<virtual>> EnterCompound_operator(context:SQLiteParser.Compound_operatorContext) : void
    + <<virtual>> ExitCompound_operator(context:SQLiteParser.Compound_operatorContext) : void
    + <<virtual>> EnterSet_clause(context:SQLiteParser.Set_clauseContext) : void
    + <<virtual>> ExitSet_clause(context:SQLiteParser.Set_clauseContext) : void
    + <<virtual>> EnterSet_stmt(context:SQLiteParser.Set_stmtContext) : void
    + <<virtual>> ExitSet_stmt(context:SQLiteParser.Set_stmtContext) : void
    + <<virtual>> EnterUpdate_stmt(context:SQLiteParser.Update_stmtContext) : void
    + <<virtual>> ExitUpdate_stmt(context:SQLiteParser.Update_stmtContext) : void
    + <<virtual>> EnterColumn_name_list(context:SQLiteParser.Column_name_listContext) : void
    + <<virtual>> ExitColumn_name_list(context:SQLiteParser.Column_name_listContext) : void
    + <<virtual>> EnterUpdate_stmt_limited(context:SQLiteParser.Update_stmt_limitedContext) : void
    + <<virtual>> ExitUpdate_stmt_limited(context:SQLiteParser.Update_stmt_limitedContext) : void
    + <<virtual>> EnterQualified_table_name(context:SQLiteParser.Qualified_table_nameContext) : void
    + <<virtual>> ExitQualified_table_name(context:SQLiteParser.Qualified_table_nameContext) : void
    + <<virtual>> EnterVacuum_stmt(context:SQLiteParser.Vacuum_stmtContext) : void
    + <<virtual>> ExitVacuum_stmt(context:SQLiteParser.Vacuum_stmtContext) : void
    + <<virtual>> EnterFilter_clause(context:SQLiteParser.Filter_clauseContext) : void
    + <<virtual>> ExitFilter_clause(context:SQLiteParser.Filter_clauseContext) : void
    + <<virtual>> EnterWindow_defn(context:SQLiteParser.Window_defnContext) : void
    + <<virtual>> ExitWindow_defn(context:SQLiteParser.Window_defnContext) : void
    + <<virtual>> EnterOver_clause(context:SQLiteParser.Over_clauseContext) : void
    + <<virtual>> ExitOver_clause(context:SQLiteParser.Over_clauseContext) : void
    + <<virtual>> EnterFrame_spec(context:SQLiteParser.Frame_specContext) : void
    + <<virtual>> ExitFrame_spec(context:SQLiteParser.Frame_specContext) : void
    + <<virtual>> EnterFrame_clause(context:SQLiteParser.Frame_clauseContext) : void
    + <<virtual>> ExitFrame_clause(context:SQLiteParser.Frame_clauseContext) : void
    + <<virtual>> EnterSimple_function_invocation(context:SQLiteParser.Simple_function_invocationContext) : void
    + <<virtual>> ExitSimple_function_invocation(context:SQLiteParser.Simple_function_invocationContext) : void
    + <<virtual>> EnterAggregate_function_invocation(context:SQLiteParser.Aggregate_function_invocationContext) : void
    + <<virtual>> ExitAggregate_function_invocation(context:SQLiteParser.Aggregate_function_invocationContext) : void
    + <<virtual>> EnterWindow_function_invocation(context:SQLiteParser.Window_function_invocationContext) : void
    + <<virtual>> ExitWindow_function_invocation(context:SQLiteParser.Window_function_invocationContext) : void
    + <<virtual>> EnterCommon_table_stmt(context:SQLiteParser.Common_table_stmtContext) : void
    + <<virtual>> ExitCommon_table_stmt(context:SQLiteParser.Common_table_stmtContext) : void
    + <<virtual>> EnterOrder_by_clause(context:SQLiteParser.Order_by_clauseContext) : void
    + <<virtual>> ExitOrder_by_clause(context:SQLiteParser.Order_by_clauseContext) : void
    + <<virtual>> EnterLimit_clause(context:SQLiteParser.Limit_clauseContext) : void
    + <<virtual>> ExitLimit_clause(context:SQLiteParser.Limit_clauseContext) : void
    + <<virtual>> EnterOffset_clause(context:SQLiteParser.Offset_clauseContext) : void
    + <<virtual>> ExitOffset_clause(context:SQLiteParser.Offset_clauseContext) : void
    + <<virtual>> EnterOrdering_term(context:SQLiteParser.Ordering_termContext) : void
    + <<virtual>> ExitOrdering_term(context:SQLiteParser.Ordering_termContext) : void
    + <<virtual>> EnterAsc_desc(context:SQLiteParser.Asc_descContext) : void
    + <<virtual>> ExitAsc_desc(context:SQLiteParser.Asc_descContext) : void
    + <<virtual>> EnterFrame_left(context:SQLiteParser.Frame_leftContext) : void
    + <<virtual>> ExitFrame_left(context:SQLiteParser.Frame_leftContext) : void
    + <<virtual>> EnterFrame_right(context:SQLiteParser.Frame_rightContext) : void
    + <<virtual>> ExitFrame_right(context:SQLiteParser.Frame_rightContext) : void
    + <<virtual>> EnterFrame_single(context:SQLiteParser.Frame_singleContext) : void
    + <<virtual>> ExitFrame_single(context:SQLiteParser.Frame_singleContext) : void
    + <<virtual>> EnterWindow_function(context:SQLiteParser.Window_functionContext) : void
    + <<virtual>> ExitWindow_function(context:SQLiteParser.Window_functionContext) : void
    + <<virtual>> EnterOffset(context:SQLiteParser.OffsetContext) : void
    + <<virtual>> ExitOffset(context:SQLiteParser.OffsetContext) : void
    + <<virtual>> EnterDefault_value(context:SQLiteParser.Default_valueContext) : void
    + <<virtual>> ExitDefault_value(context:SQLiteParser.Default_valueContext) : void
    + <<virtual>> EnterPartition_by(context:SQLiteParser.Partition_byContext) : void
    + <<virtual>> ExitPartition_by(context:SQLiteParser.Partition_byContext) : void
    + <<virtual>> EnterOrder_by_expr(context:SQLiteParser.Order_by_exprContext) : void
    + <<virtual>> ExitOrder_by_expr(context:SQLiteParser.Order_by_exprContext) : void
    + <<virtual>> EnterOrder_by_expr_asc_desc(context:SQLiteParser.Order_by_expr_asc_descContext) : void
    + <<virtual>> ExitOrder_by_expr_asc_desc(context:SQLiteParser.Order_by_expr_asc_descContext) : void
    + <<virtual>> EnterExpr_asc_desc(context:SQLiteParser.Expr_asc_descContext) : void
    + <<virtual>> ExitExpr_asc_desc(context:SQLiteParser.Expr_asc_descContext) : void
    + <<virtual>> EnterInitial_select(context:SQLiteParser.Initial_selectContext) : void
    + <<virtual>> ExitInitial_select(context:SQLiteParser.Initial_selectContext) : void
    + <<virtual>> EnterRecursive_select(context:SQLiteParser.Recursive_selectContext) : void
    + <<virtual>> ExitRecursive_select(context:SQLiteParser.Recursive_selectContext) : void
    + <<virtual>> EnterUnary_operator(context:SQLiteParser.Unary_operatorContext) : void
    + <<virtual>> ExitUnary_operator(context:SQLiteParser.Unary_operatorContext) : void
    + <<virtual>> EnterError_message(context:SQLiteParser.Error_messageContext) : void
    + <<virtual>> ExitError_message(context:SQLiteParser.Error_messageContext) : void
    + <<virtual>> EnterModule_argument(context:SQLiteParser.Module_argumentContext) : void
    + <<virtual>> ExitModule_argument(context:SQLiteParser.Module_argumentContext) : void
    + <<virtual>> EnterColumn_alias(context:SQLiteParser.Column_aliasContext) : void
    + <<virtual>> ExitColumn_alias(context:SQLiteParser.Column_aliasContext) : void
    + <<virtual>> EnterKeyword(context:SQLiteParser.KeywordContext) : void
    + <<virtual>> ExitKeyword(context:SQLiteParser.KeywordContext) : void
    + <<virtual>> EnterName(context:SQLiteParser.NameContext) : void
    + <<virtual>> ExitName(context:SQLiteParser.NameContext) : void
    + <<virtual>> EnterFunction_name(context:SQLiteParser.Function_nameContext) : void
    + <<virtual>> ExitFunction_name(context:SQLiteParser.Function_nameContext) : void
    + <<virtual>> EnterSchema_name(context:SQLiteParser.Schema_nameContext) : void
    + <<virtual>> ExitSchema_name(context:SQLiteParser.Schema_nameContext) : void
    + <<virtual>> EnterTable_name(context:SQLiteParser.Table_nameContext) : void
    + <<virtual>> ExitTable_name(context:SQLiteParser.Table_nameContext) : void
    + <<virtual>> EnterTable_or_index_name(context:SQLiteParser.Table_or_index_nameContext) : void
    + <<virtual>> ExitTable_or_index_name(context:SQLiteParser.Table_or_index_nameContext) : void
    + <<virtual>> EnterColumn_name(context:SQLiteParser.Column_nameContext) : void
    + <<virtual>> ExitColumn_name(context:SQLiteParser.Column_nameContext) : void
    + <<virtual>> EnterCollation_name(context:SQLiteParser.Collation_nameContext) : void
    + <<virtual>> ExitCollation_name(context:SQLiteParser.Collation_nameContext) : void
    + <<virtual>> EnterForeign_table(context:SQLiteParser.Foreign_tableContext) : void
    + <<virtual>> ExitForeign_table(context:SQLiteParser.Foreign_tableContext) : void
    + <<virtual>> EnterIndex_name(context:SQLiteParser.Index_nameContext) : void
    + <<virtual>> ExitIndex_name(context:SQLiteParser.Index_nameContext) : void
    + <<virtual>> EnterTrigger_name(context:SQLiteParser.Trigger_nameContext) : void
    + <<virtual>> ExitTrigger_name(context:SQLiteParser.Trigger_nameContext) : void
    + <<virtual>> EnterView_name(context:SQLiteParser.View_nameContext) : void
    + <<virtual>> ExitView_name(context:SQLiteParser.View_nameContext) : void
    + <<virtual>> EnterModule_name(context:SQLiteParser.Module_nameContext) : void
    + <<virtual>> ExitModule_name(context:SQLiteParser.Module_nameContext) : void
    + <<virtual>> EnterPragma_name(context:SQLiteParser.Pragma_nameContext) : void
    + <<virtual>> ExitPragma_name(context:SQLiteParser.Pragma_nameContext) : void
    + <<virtual>> EnterSavepoint_name(context:SQLiteParser.Savepoint_nameContext) : void
    + <<virtual>> ExitSavepoint_name(context:SQLiteParser.Savepoint_nameContext) : void
    + <<virtual>> EnterTable_alias(context:SQLiteParser.Table_aliasContext) : void
    + <<virtual>> ExitTable_alias(context:SQLiteParser.Table_aliasContext) : void
    + <<virtual>> EnterTransaction_name(context:SQLiteParser.Transaction_nameContext) : void
    + <<virtual>> ExitTransaction_name(context:SQLiteParser.Transaction_nameContext) : void
    + <<virtual>> EnterWindow_name(context:SQLiteParser.Window_nameContext) : void
    + <<virtual>> ExitWindow_name(context:SQLiteParser.Window_nameContext) : void
    + <<virtual>> EnterAlias(context:SQLiteParser.AliasContext) : void
    + <<virtual>> ExitAlias(context:SQLiteParser.AliasContext) : void
    + <<virtual>> EnterFilename(context:SQLiteParser.FilenameContext) : void
    + <<virtual>> ExitFilename(context:SQLiteParser.FilenameContext) : void
    + <<virtual>> EnterBase_window_name(context:SQLiteParser.Base_window_nameContext) : void
    + <<virtual>> ExitBase_window_name(context:SQLiteParser.Base_window_nameContext) : void
    + <<virtual>> EnterSimple_func(context:SQLiteParser.Simple_funcContext) : void
    + <<virtual>> ExitSimple_func(context:SQLiteParser.Simple_funcContext) : void
    + <<virtual>> EnterAggregate_func(context:SQLiteParser.Aggregate_funcContext) : void
    + <<virtual>> ExitAggregate_func(context:SQLiteParser.Aggregate_funcContext) : void
    + <<virtual>> EnterTable_function_name(context:SQLiteParser.Table_function_nameContext) : void
    + <<virtual>> ExitTable_function_name(context:SQLiteParser.Table_function_nameContext) : void
    + <<virtual>> EnterAny_name(context:SQLiteParser.Any_nameContext) : void
    + <<virtual>> ExitAny_name(context:SQLiteParser.Any_nameContext) : void
    + <<virtual>> EnterEveryRule(context:ParserRuleContext) : void
    + <<virtual>> ExitEveryRule(context:ParserRuleContext) : void
    + <<virtual>> VisitTerminal(node:ITerminalNode) : void
    + <<virtual>> VisitErrorNode(node:IErrorNode) : void
}
ISQLiteParserListener <|-- SQLiteParserBaseListener
@enduml
