@startuml
interface ISQLiteParserListener {
    EnterParse(context:SQLiteParser.ParseContext) : void
    ExitParse(context:SQLiteParser.ParseContext) : void
    EnterSql_stmt_list(context:SQLiteParser.Sql_stmt_listContext) : void
    ExitSql_stmt_list(context:SQLiteParser.Sql_stmt_listContext) : void
    EnterSql_stmt(context:SQLiteParser.Sql_stmtContext) : void
    ExitSql_stmt(context:SQLiteParser.Sql_stmtContext) : void
    EnterAlter_table_stmt(context:SQLiteParser.Alter_table_stmtContext) : void
    ExitAlter_table_stmt(context:SQLiteParser.Alter_table_stmtContext) : void
    EnterAnalyze_stmt(context:SQLiteParser.Analyze_stmtContext) : void
    ExitAnalyze_stmt(context:SQLiteParser.Analyze_stmtContext) : void
    EnterAttach_stmt(context:SQLiteParser.Attach_stmtContext) : void
    ExitAttach_stmt(context:SQLiteParser.Attach_stmtContext) : void
    EnterBegin_stmt(context:SQLiteParser.Begin_stmtContext) : void
    ExitBegin_stmt(context:SQLiteParser.Begin_stmtContext) : void
    EnterCommit_stmt(context:SQLiteParser.Commit_stmtContext) : void
    ExitCommit_stmt(context:SQLiteParser.Commit_stmtContext) : void
    EnterRollback_stmt(context:SQLiteParser.Rollback_stmtContext) : void
    ExitRollback_stmt(context:SQLiteParser.Rollback_stmtContext) : void
    EnterSavepoint_stmt(context:SQLiteParser.Savepoint_stmtContext) : void
    ExitSavepoint_stmt(context:SQLiteParser.Savepoint_stmtContext) : void
    EnterRelease_stmt(context:SQLiteParser.Release_stmtContext) : void
    ExitRelease_stmt(context:SQLiteParser.Release_stmtContext) : void
    EnterCreate_index_stmt(context:SQLiteParser.Create_index_stmtContext) : void
    ExitCreate_index_stmt(context:SQLiteParser.Create_index_stmtContext) : void
    EnterIndexed_column(context:SQLiteParser.Indexed_columnContext) : void
    ExitIndexed_column(context:SQLiteParser.Indexed_columnContext) : void
    EnterCreate_table_stmt(context:SQLiteParser.Create_table_stmtContext) : void
    ExitCreate_table_stmt(context:SQLiteParser.Create_table_stmtContext) : void
    EnterColumn_def(context:SQLiteParser.Column_defContext) : void
    ExitColumn_def(context:SQLiteParser.Column_defContext) : void
    EnterType_name(context:SQLiteParser.Type_nameContext) : void
    ExitType_name(context:SQLiteParser.Type_nameContext) : void
    EnterColumn_constraint(context:SQLiteParser.Column_constraintContext) : void
    ExitColumn_constraint(context:SQLiteParser.Column_constraintContext) : void
    EnterSigned_number(context:SQLiteParser.Signed_numberContext) : void
    ExitSigned_number(context:SQLiteParser.Signed_numberContext) : void
    EnterTable_constraint(context:SQLiteParser.Table_constraintContext) : void
    ExitTable_constraint(context:SQLiteParser.Table_constraintContext) : void
    EnterForeign_key_clause(context:SQLiteParser.Foreign_key_clauseContext) : void
    ExitForeign_key_clause(context:SQLiteParser.Foreign_key_clauseContext) : void
    EnterConflict_clause(context:SQLiteParser.Conflict_clauseContext) : void
    ExitConflict_clause(context:SQLiteParser.Conflict_clauseContext) : void
    EnterCreate_trigger_stmt(context:SQLiteParser.Create_trigger_stmtContext) : void
    ExitCreate_trigger_stmt(context:SQLiteParser.Create_trigger_stmtContext) : void
    EnterCreate_view_stmt(context:SQLiteParser.Create_view_stmtContext) : void
    ExitCreate_view_stmt(context:SQLiteParser.Create_view_stmtContext) : void
    EnterCreate_virtual_table_stmt(context:SQLiteParser.Create_virtual_table_stmtContext) : void
    ExitCreate_virtual_table_stmt(context:SQLiteParser.Create_virtual_table_stmtContext) : void
    EnterWith_clause(context:SQLiteParser.With_clauseContext) : void
    ExitWith_clause(context:SQLiteParser.With_clauseContext) : void
    EnterCte_table_name(context:SQLiteParser.Cte_table_nameContext) : void
    ExitCte_table_name(context:SQLiteParser.Cte_table_nameContext) : void
    EnterRecursive_cte(context:SQLiteParser.Recursive_cteContext) : void
    ExitRecursive_cte(context:SQLiteParser.Recursive_cteContext) : void
    EnterCommon_table_expression(context:SQLiteParser.Common_table_expressionContext) : void
    ExitCommon_table_expression(context:SQLiteParser.Common_table_expressionContext) : void
    EnterDelete_stmt(context:SQLiteParser.Delete_stmtContext) : void
    ExitDelete_stmt(context:SQLiteParser.Delete_stmtContext) : void
    EnterDelete_stmt_limited(context:SQLiteParser.Delete_stmt_limitedContext) : void
    ExitDelete_stmt_limited(context:SQLiteParser.Delete_stmt_limitedContext) : void
    EnterDetach_stmt(context:SQLiteParser.Detach_stmtContext) : void
    ExitDetach_stmt(context:SQLiteParser.Detach_stmtContext) : void
    EnterDrop_stmt(context:SQLiteParser.Drop_stmtContext) : void
    ExitDrop_stmt(context:SQLiteParser.Drop_stmtContext) : void
    EnterExpr(context:SQLiteParser.ExprContext) : void
    ExitExpr(context:SQLiteParser.ExprContext) : void
    EnterRaise_function(context:SQLiteParser.Raise_functionContext) : void
    ExitRaise_function(context:SQLiteParser.Raise_functionContext) : void
    EnterLiteral_value(context:SQLiteParser.Literal_valueContext) : void
    ExitLiteral_value(context:SQLiteParser.Literal_valueContext) : void
    EnterColumns_clause(context:SQLiteParser.Columns_clauseContext) : void
    ExitColumns_clause(context:SQLiteParser.Columns_clauseContext) : void
    EnterInsert_stmt(context:SQLiteParser.Insert_stmtContext) : void
    ExitInsert_stmt(context:SQLiteParser.Insert_stmtContext) : void
    EnterReturning_clause(context:SQLiteParser.Returning_clauseContext) : void
    ExitReturning_clause(context:SQLiteParser.Returning_clauseContext) : void
    EnterUpsert_clause(context:SQLiteParser.Upsert_clauseContext) : void
    ExitUpsert_clause(context:SQLiteParser.Upsert_clauseContext) : void
    EnterPragma_stmt(context:SQLiteParser.Pragma_stmtContext) : void
    ExitPragma_stmt(context:SQLiteParser.Pragma_stmtContext) : void
    EnterPragma_value(context:SQLiteParser.Pragma_valueContext) : void
    ExitPragma_value(context:SQLiteParser.Pragma_valueContext) : void
    EnterReindex_stmt(context:SQLiteParser.Reindex_stmtContext) : void
    ExitReindex_stmt(context:SQLiteParser.Reindex_stmtContext) : void
    EnterSelect_stmt(context:SQLiteParser.Select_stmtContext) : void
    ExitSelect_stmt(context:SQLiteParser.Select_stmtContext) : void
    EnterJoin_stmt(context:SQLiteParser.Join_stmtContext) : void
    ExitJoin_stmt(context:SQLiteParser.Join_stmtContext) : void
    EnterJoin_clause(context:SQLiteParser.Join_clauseContext) : void
    ExitJoin_clause(context:SQLiteParser.Join_clauseContext) : void
    EnterWhere_clause(context:SQLiteParser.Where_clauseContext) : void
    ExitWhere_clause(context:SQLiteParser.Where_clauseContext) : void
    EnterGroup_by_clause(context:SQLiteParser.Group_by_clauseContext) : void
    ExitGroup_by_clause(context:SQLiteParser.Group_by_clauseContext) : void
    EnterHaving_clause(context:SQLiteParser.Having_clauseContext) : void
    ExitHaving_clause(context:SQLiteParser.Having_clauseContext) : void
    EnterValues_clause(context:SQLiteParser.Values_clauseContext) : void
    ExitValues_clause(context:SQLiteParser.Values_clauseContext) : void
    EnterValues_stmt(context:SQLiteParser.Values_stmtContext) : void
    ExitValues_stmt(context:SQLiteParser.Values_stmtContext) : void
    EnterFrom_clause(context:SQLiteParser.From_clauseContext) : void
    ExitFrom_clause(context:SQLiteParser.From_clauseContext) : void
    EnterWindow_clause(context:SQLiteParser.Window_clauseContext) : void
    ExitWindow_clause(context:SQLiteParser.Window_clauseContext) : void
    EnterSelect_core(context:SQLiteParser.Select_coreContext) : void
    ExitSelect_core(context:SQLiteParser.Select_coreContext) : void
    EnterFactored_select_stmt(context:SQLiteParser.Factored_select_stmtContext) : void
    ExitFactored_select_stmt(context:SQLiteParser.Factored_select_stmtContext) : void
    EnterSimple_select_stmt(context:SQLiteParser.Simple_select_stmtContext) : void
    ExitSimple_select_stmt(context:SQLiteParser.Simple_select_stmtContext) : void
    EnterCompound_select_stmt(context:SQLiteParser.Compound_select_stmtContext) : void
    ExitCompound_select_stmt(context:SQLiteParser.Compound_select_stmtContext) : void
    EnterTable_or_subquery(context:SQLiteParser.Table_or_subqueryContext) : void
    ExitTable_or_subquery(context:SQLiteParser.Table_or_subqueryContext) : void
    EnterResult_column(context:SQLiteParser.Result_columnContext) : void
    ExitResult_column(context:SQLiteParser.Result_columnContext) : void
    EnterJoin_operator(context:SQLiteParser.Join_operatorContext) : void
    ExitJoin_operator(context:SQLiteParser.Join_operatorContext) : void
    EnterJoin_constraint(context:SQLiteParser.Join_constraintContext) : void
    ExitJoin_constraint(context:SQLiteParser.Join_constraintContext) : void
    EnterCompound_operator(context:SQLiteParser.Compound_operatorContext) : void
    ExitCompound_operator(context:SQLiteParser.Compound_operatorContext) : void
    EnterSet_clause(context:SQLiteParser.Set_clauseContext) : void
    ExitSet_clause(context:SQLiteParser.Set_clauseContext) : void
    EnterSet_stmt(context:SQLiteParser.Set_stmtContext) : void
    ExitSet_stmt(context:SQLiteParser.Set_stmtContext) : void
    EnterUpdate_stmt(context:SQLiteParser.Update_stmtContext) : void
    ExitUpdate_stmt(context:SQLiteParser.Update_stmtContext) : void
    EnterColumn_name_list(context:SQLiteParser.Column_name_listContext) : void
    ExitColumn_name_list(context:SQLiteParser.Column_name_listContext) : void
    EnterUpdate_stmt_limited(context:SQLiteParser.Update_stmt_limitedContext) : void
    ExitUpdate_stmt_limited(context:SQLiteParser.Update_stmt_limitedContext) : void
    EnterQualified_table_name(context:SQLiteParser.Qualified_table_nameContext) : void
    ExitQualified_table_name(context:SQLiteParser.Qualified_table_nameContext) : void
    EnterVacuum_stmt(context:SQLiteParser.Vacuum_stmtContext) : void
    ExitVacuum_stmt(context:SQLiteParser.Vacuum_stmtContext) : void
    EnterFilter_clause(context:SQLiteParser.Filter_clauseContext) : void
    ExitFilter_clause(context:SQLiteParser.Filter_clauseContext) : void
    EnterWindow_defn(context:SQLiteParser.Window_defnContext) : void
    ExitWindow_defn(context:SQLiteParser.Window_defnContext) : void
    EnterOver_clause(context:SQLiteParser.Over_clauseContext) : void
    ExitOver_clause(context:SQLiteParser.Over_clauseContext) : void
    EnterFrame_spec(context:SQLiteParser.Frame_specContext) : void
    ExitFrame_spec(context:SQLiteParser.Frame_specContext) : void
    EnterFrame_clause(context:SQLiteParser.Frame_clauseContext) : void
    ExitFrame_clause(context:SQLiteParser.Frame_clauseContext) : void
    EnterSimple_function_invocation(context:SQLiteParser.Simple_function_invocationContext) : void
    ExitSimple_function_invocation(context:SQLiteParser.Simple_function_invocationContext) : void
    EnterAggregate_function_invocation(context:SQLiteParser.Aggregate_function_invocationContext) : void
    ExitAggregate_function_invocation(context:SQLiteParser.Aggregate_function_invocationContext) : void
    EnterWindow_function_invocation(context:SQLiteParser.Window_function_invocationContext) : void
    ExitWindow_function_invocation(context:SQLiteParser.Window_function_invocationContext) : void
    EnterCommon_table_stmt(context:SQLiteParser.Common_table_stmtContext) : void
    ExitCommon_table_stmt(context:SQLiteParser.Common_table_stmtContext) : void
    EnterOrder_by_clause(context:SQLiteParser.Order_by_clauseContext) : void
    ExitOrder_by_clause(context:SQLiteParser.Order_by_clauseContext) : void
    EnterLimit_clause(context:SQLiteParser.Limit_clauseContext) : void
    ExitLimit_clause(context:SQLiteParser.Limit_clauseContext) : void
    EnterOffset_clause(context:SQLiteParser.Offset_clauseContext) : void
    ExitOffset_clause(context:SQLiteParser.Offset_clauseContext) : void
    EnterOrdering_term(context:SQLiteParser.Ordering_termContext) : void
    ExitOrdering_term(context:SQLiteParser.Ordering_termContext) : void
    EnterAsc_desc(context:SQLiteParser.Asc_descContext) : void
    ExitAsc_desc(context:SQLiteParser.Asc_descContext) : void
    EnterFrame_left(context:SQLiteParser.Frame_leftContext) : void
    ExitFrame_left(context:SQLiteParser.Frame_leftContext) : void
    EnterFrame_right(context:SQLiteParser.Frame_rightContext) : void
    ExitFrame_right(context:SQLiteParser.Frame_rightContext) : void
    EnterFrame_single(context:SQLiteParser.Frame_singleContext) : void
    ExitFrame_single(context:SQLiteParser.Frame_singleContext) : void
    EnterWindow_function(context:SQLiteParser.Window_functionContext) : void
    ExitWindow_function(context:SQLiteParser.Window_functionContext) : void
    EnterOffset(context:SQLiteParser.OffsetContext) : void
    ExitOffset(context:SQLiteParser.OffsetContext) : void
    EnterDefault_value(context:SQLiteParser.Default_valueContext) : void
    ExitDefault_value(context:SQLiteParser.Default_valueContext) : void
    EnterPartition_by(context:SQLiteParser.Partition_byContext) : void
    ExitPartition_by(context:SQLiteParser.Partition_byContext) : void
    EnterOrder_by_expr(context:SQLiteParser.Order_by_exprContext) : void
    ExitOrder_by_expr(context:SQLiteParser.Order_by_exprContext) : void
    EnterOrder_by_expr_asc_desc(context:SQLiteParser.Order_by_expr_asc_descContext) : void
    ExitOrder_by_expr_asc_desc(context:SQLiteParser.Order_by_expr_asc_descContext) : void
    EnterExpr_asc_desc(context:SQLiteParser.Expr_asc_descContext) : void
    ExitExpr_asc_desc(context:SQLiteParser.Expr_asc_descContext) : void
    EnterInitial_select(context:SQLiteParser.Initial_selectContext) : void
    ExitInitial_select(context:SQLiteParser.Initial_selectContext) : void
    EnterRecursive_select(context:SQLiteParser.Recursive_selectContext) : void
    ExitRecursive_select(context:SQLiteParser.Recursive_selectContext) : void
    EnterUnary_operator(context:SQLiteParser.Unary_operatorContext) : void
    ExitUnary_operator(context:SQLiteParser.Unary_operatorContext) : void
    EnterError_message(context:SQLiteParser.Error_messageContext) : void
    ExitError_message(context:SQLiteParser.Error_messageContext) : void
    EnterModule_argument(context:SQLiteParser.Module_argumentContext) : void
    ExitModule_argument(context:SQLiteParser.Module_argumentContext) : void
    EnterColumn_alias(context:SQLiteParser.Column_aliasContext) : void
    ExitColumn_alias(context:SQLiteParser.Column_aliasContext) : void
    EnterKeyword(context:SQLiteParser.KeywordContext) : void
    ExitKeyword(context:SQLiteParser.KeywordContext) : void
    EnterName(context:SQLiteParser.NameContext) : void
    ExitName(context:SQLiteParser.NameContext) : void
    EnterFunction_name(context:SQLiteParser.Function_nameContext) : void
    ExitFunction_name(context:SQLiteParser.Function_nameContext) : void
    EnterSchema_name(context:SQLiteParser.Schema_nameContext) : void
    ExitSchema_name(context:SQLiteParser.Schema_nameContext) : void
    EnterTable_name(context:SQLiteParser.Table_nameContext) : void
    ExitTable_name(context:SQLiteParser.Table_nameContext) : void
    EnterTable_or_index_name(context:SQLiteParser.Table_or_index_nameContext) : void
    ExitTable_or_index_name(context:SQLiteParser.Table_or_index_nameContext) : void
    EnterColumn_name(context:SQLiteParser.Column_nameContext) : void
    ExitColumn_name(context:SQLiteParser.Column_nameContext) : void
    EnterCollation_name(context:SQLiteParser.Collation_nameContext) : void
    ExitCollation_name(context:SQLiteParser.Collation_nameContext) : void
    EnterForeign_table(context:SQLiteParser.Foreign_tableContext) : void
    ExitForeign_table(context:SQLiteParser.Foreign_tableContext) : void
    EnterIndex_name(context:SQLiteParser.Index_nameContext) : void
    ExitIndex_name(context:SQLiteParser.Index_nameContext) : void
    EnterTrigger_name(context:SQLiteParser.Trigger_nameContext) : void
    ExitTrigger_name(context:SQLiteParser.Trigger_nameContext) : void
    EnterView_name(context:SQLiteParser.View_nameContext) : void
    ExitView_name(context:SQLiteParser.View_nameContext) : void
    EnterModule_name(context:SQLiteParser.Module_nameContext) : void
    ExitModule_name(context:SQLiteParser.Module_nameContext) : void
    EnterPragma_name(context:SQLiteParser.Pragma_nameContext) : void
    ExitPragma_name(context:SQLiteParser.Pragma_nameContext) : void
    EnterSavepoint_name(context:SQLiteParser.Savepoint_nameContext) : void
    ExitSavepoint_name(context:SQLiteParser.Savepoint_nameContext) : void
    EnterTable_alias(context:SQLiteParser.Table_aliasContext) : void
    ExitTable_alias(context:SQLiteParser.Table_aliasContext) : void
    EnterTransaction_name(context:SQLiteParser.Transaction_nameContext) : void
    ExitTransaction_name(context:SQLiteParser.Transaction_nameContext) : void
    EnterWindow_name(context:SQLiteParser.Window_nameContext) : void
    ExitWindow_name(context:SQLiteParser.Window_nameContext) : void
    EnterAlias(context:SQLiteParser.AliasContext) : void
    ExitAlias(context:SQLiteParser.AliasContext) : void
    EnterFilename(context:SQLiteParser.FilenameContext) : void
    ExitFilename(context:SQLiteParser.FilenameContext) : void
    EnterBase_window_name(context:SQLiteParser.Base_window_nameContext) : void
    ExitBase_window_name(context:SQLiteParser.Base_window_nameContext) : void
    EnterSimple_func(context:SQLiteParser.Simple_funcContext) : void
    ExitSimple_func(context:SQLiteParser.Simple_funcContext) : void
    EnterAggregate_func(context:SQLiteParser.Aggregate_funcContext) : void
    ExitAggregate_func(context:SQLiteParser.Aggregate_funcContext) : void
    EnterTable_function_name(context:SQLiteParser.Table_function_nameContext) : void
    ExitTable_function_name(context:SQLiteParser.Table_function_nameContext) : void
    EnterAny_name(context:SQLiteParser.Any_nameContext) : void
    ExitAny_name(context:SQLiteParser.Any_nameContext) : void
}
IParseTreeListener <|-- ISQLiteParserListener
@enduml
