@startuml
class "SQLiteParserBaseVisitor`1"<Result> <<partial>> {
    + <<virtual>> VisitParse(context:SQLiteParser.ParseContext) : Result
    + <<virtual>> VisitSql_stmt_list(context:SQLiteParser.Sql_stmt_listContext) : Result
    + <<virtual>> VisitSql_stmt(context:SQLiteParser.Sql_stmtContext) : Result
    + <<virtual>> VisitAlter_table_stmt(context:SQLiteParser.Alter_table_stmtContext) : Result
    + <<virtual>> VisitAnalyze_stmt(context:SQLiteParser.Analyze_stmtContext) : Result
    + <<virtual>> VisitAttach_stmt(context:SQLiteParser.Attach_stmtContext) : Result
    + <<virtual>> VisitBegin_stmt(context:SQLiteParser.Begin_stmtContext) : Result
    + <<virtual>> VisitCommit_stmt(context:SQLiteParser.Commit_stmtContext) : Result
    + <<virtual>> VisitRollback_stmt(context:SQLiteParser.Rollback_stmtContext) : Result
    + <<virtual>> VisitSavepoint_stmt(context:SQLiteParser.Savepoint_stmtContext) : Result
    + <<virtual>> VisitRelease_stmt(context:SQLiteParser.Release_stmtContext) : Result
    + <<virtual>> VisitCreate_index_stmt(context:SQLiteParser.Create_index_stmtContext) : Result
    + <<virtual>> VisitIndexed_column(context:SQLiteParser.Indexed_columnContext) : Result
    + <<virtual>> VisitCreate_table_stmt(context:SQLiteParser.Create_table_stmtContext) : Result
    + <<virtual>> VisitColumn_def(context:SQLiteParser.Column_defContext) : Result
    + <<virtual>> VisitType_name(context:SQLiteParser.Type_nameContext) : Result
    + <<virtual>> VisitColumn_constraint(context:SQLiteParser.Column_constraintContext) : Result
    + <<virtual>> VisitSigned_number(context:SQLiteParser.Signed_numberContext) : Result
    + <<virtual>> VisitTable_constraint(context:SQLiteParser.Table_constraintContext) : Result
    + <<virtual>> VisitForeign_key_clause(context:SQLiteParser.Foreign_key_clauseContext) : Result
    + <<virtual>> VisitConflict_clause(context:SQLiteParser.Conflict_clauseContext) : Result
    + <<virtual>> VisitCreate_trigger_stmt(context:SQLiteParser.Create_trigger_stmtContext) : Result
    + <<virtual>> VisitCreate_view_stmt(context:SQLiteParser.Create_view_stmtContext) : Result
    + <<virtual>> VisitCreate_virtual_table_stmt(context:SQLiteParser.Create_virtual_table_stmtContext) : Result
    + <<virtual>> VisitWith_clause(context:SQLiteParser.With_clauseContext) : Result
    + <<virtual>> VisitCte_table_name(context:SQLiteParser.Cte_table_nameContext) : Result
    + <<virtual>> VisitRecursive_cte(context:SQLiteParser.Recursive_cteContext) : Result
    + <<virtual>> VisitCommon_table_expression(context:SQLiteParser.Common_table_expressionContext) : Result
    + <<virtual>> VisitDelete_stmt(context:SQLiteParser.Delete_stmtContext) : Result
    + <<virtual>> VisitDelete_stmt_limited(context:SQLiteParser.Delete_stmt_limitedContext) : Result
    + <<virtual>> VisitDetach_stmt(context:SQLiteParser.Detach_stmtContext) : Result
    + <<virtual>> VisitDrop_stmt(context:SQLiteParser.Drop_stmtContext) : Result
    + <<virtual>> VisitExpr(context:SQLiteParser.ExprContext) : Result
    + <<virtual>> VisitRaise_function(context:SQLiteParser.Raise_functionContext) : Result
    + <<virtual>> VisitLiteral_value(context:SQLiteParser.Literal_valueContext) : Result
    + <<virtual>> VisitColumns_clause(context:SQLiteParser.Columns_clauseContext) : Result
    + <<virtual>> VisitInsert_stmt(context:SQLiteParser.Insert_stmtContext) : Result
    + <<virtual>> VisitReturning_clause(context:SQLiteParser.Returning_clauseContext) : Result
    + <<virtual>> VisitUpsert_clause(context:SQLiteParser.Upsert_clauseContext) : Result
    + <<virtual>> VisitPragma_stmt(context:SQLiteParser.Pragma_stmtContext) : Result
    + <<virtual>> VisitPragma_value(context:SQLiteParser.Pragma_valueContext) : Result
    + <<virtual>> VisitReindex_stmt(context:SQLiteParser.Reindex_stmtContext) : Result
    + <<virtual>> VisitSelect_stmt(context:SQLiteParser.Select_stmtContext) : Result
    + <<virtual>> VisitJoin_stmt(context:SQLiteParser.Join_stmtContext) : Result
    + <<virtual>> VisitJoin_clause(context:SQLiteParser.Join_clauseContext) : Result
    + <<virtual>> VisitWhere_clause(context:SQLiteParser.Where_clauseContext) : Result
    + <<virtual>> VisitGroup_by_clause(context:SQLiteParser.Group_by_clauseContext) : Result
    + <<virtual>> VisitHaving_clause(context:SQLiteParser.Having_clauseContext) : Result
    + <<virtual>> VisitValues_clause(context:SQLiteParser.Values_clauseContext) : Result
    + <<virtual>> VisitValues_stmt(context:SQLiteParser.Values_stmtContext) : Result
    + <<virtual>> VisitFrom_clause(context:SQLiteParser.From_clauseContext) : Result
    + <<virtual>> VisitWindow_clause(context:SQLiteParser.Window_clauseContext) : Result
    + <<virtual>> VisitSelect_core(context:SQLiteParser.Select_coreContext) : Result
    + <<virtual>> VisitFactored_select_stmt(context:SQLiteParser.Factored_select_stmtContext) : Result
    + <<virtual>> VisitSimple_select_stmt(context:SQLiteParser.Simple_select_stmtContext) : Result
    + <<virtual>> VisitCompound_select_stmt(context:SQLiteParser.Compound_select_stmtContext) : Result
    + <<virtual>> VisitTable_or_subquery(context:SQLiteParser.Table_or_subqueryContext) : Result
    + <<virtual>> VisitResult_column(context:SQLiteParser.Result_columnContext) : Result
    + <<virtual>> VisitJoin_operator(context:SQLiteParser.Join_operatorContext) : Result
    + <<virtual>> VisitJoin_constraint(context:SQLiteParser.Join_constraintContext) : Result
    + <<virtual>> VisitCompound_operator(context:SQLiteParser.Compound_operatorContext) : Result
    + <<virtual>> VisitSet_clause(context:SQLiteParser.Set_clauseContext) : Result
    + <<virtual>> VisitSet_stmt(context:SQLiteParser.Set_stmtContext) : Result
    + <<virtual>> VisitUpdate_stmt(context:SQLiteParser.Update_stmtContext) : Result
    + <<virtual>> VisitColumn_name_list(context:SQLiteParser.Column_name_listContext) : Result
    + <<virtual>> VisitUpdate_stmt_limited(context:SQLiteParser.Update_stmt_limitedContext) : Result
    + <<virtual>> VisitQualified_table_name(context:SQLiteParser.Qualified_table_nameContext) : Result
    + <<virtual>> VisitVacuum_stmt(context:SQLiteParser.Vacuum_stmtContext) : Result
    + <<virtual>> VisitFilter_clause(context:SQLiteParser.Filter_clauseContext) : Result
    + <<virtual>> VisitWindow_defn(context:SQLiteParser.Window_defnContext) : Result
    + <<virtual>> VisitOver_clause(context:SQLiteParser.Over_clauseContext) : Result
    + <<virtual>> VisitFrame_spec(context:SQLiteParser.Frame_specContext) : Result
    + <<virtual>> VisitFrame_clause(context:SQLiteParser.Frame_clauseContext) : Result
    + <<virtual>> VisitSimple_function_invocation(context:SQLiteParser.Simple_function_invocationContext) : Result
    + <<virtual>> VisitAggregate_function_invocation(context:SQLiteParser.Aggregate_function_invocationContext) : Result
    + <<virtual>> VisitWindow_function_invocation(context:SQLiteParser.Window_function_invocationContext) : Result
    + <<virtual>> VisitCommon_table_stmt(context:SQLiteParser.Common_table_stmtContext) : Result
    + <<virtual>> VisitOrder_by_clause(context:SQLiteParser.Order_by_clauseContext) : Result
    + <<virtual>> VisitLimit_clause(context:SQLiteParser.Limit_clauseContext) : Result
    + <<virtual>> VisitOffset_clause(context:SQLiteParser.Offset_clauseContext) : Result
    + <<virtual>> VisitOrdering_term(context:SQLiteParser.Ordering_termContext) : Result
    + <<virtual>> VisitAsc_desc(context:SQLiteParser.Asc_descContext) : Result
    + <<virtual>> VisitFrame_left(context:SQLiteParser.Frame_leftContext) : Result
    + <<virtual>> VisitFrame_right(context:SQLiteParser.Frame_rightContext) : Result
    + <<virtual>> VisitFrame_single(context:SQLiteParser.Frame_singleContext) : Result
    + <<virtual>> VisitWindow_function(context:SQLiteParser.Window_functionContext) : Result
    + <<virtual>> VisitOffset(context:SQLiteParser.OffsetContext) : Result
    + <<virtual>> VisitDefault_value(context:SQLiteParser.Default_valueContext) : Result
    + <<virtual>> VisitPartition_by(context:SQLiteParser.Partition_byContext) : Result
    + <<virtual>> VisitOrder_by_expr(context:SQLiteParser.Order_by_exprContext) : Result
    + <<virtual>> VisitOrder_by_expr_asc_desc(context:SQLiteParser.Order_by_expr_asc_descContext) : Result
    + <<virtual>> VisitExpr_asc_desc(context:SQLiteParser.Expr_asc_descContext) : Result
    + <<virtual>> VisitInitial_select(context:SQLiteParser.Initial_selectContext) : Result
    + <<virtual>> VisitRecursive_select(context:SQLiteParser.Recursive_selectContext) : Result
    + <<virtual>> VisitUnary_operator(context:SQLiteParser.Unary_operatorContext) : Result
    + <<virtual>> VisitError_message(context:SQLiteParser.Error_messageContext) : Result
    + <<virtual>> VisitModule_argument(context:SQLiteParser.Module_argumentContext) : Result
    + <<virtual>> VisitColumn_alias(context:SQLiteParser.Column_aliasContext) : Result
    + <<virtual>> VisitKeyword(context:SQLiteParser.KeywordContext) : Result
    + <<virtual>> VisitName(context:SQLiteParser.NameContext) : Result
    + <<virtual>> VisitFunction_name(context:SQLiteParser.Function_nameContext) : Result
    + <<virtual>> VisitSchema_name(context:SQLiteParser.Schema_nameContext) : Result
    + <<virtual>> VisitTable_name(context:SQLiteParser.Table_nameContext) : Result
    + <<virtual>> VisitTable_or_index_name(context:SQLiteParser.Table_or_index_nameContext) : Result
    + <<virtual>> VisitColumn_name(context:SQLiteParser.Column_nameContext) : Result
    + <<virtual>> VisitCollation_name(context:SQLiteParser.Collation_nameContext) : Result
    + <<virtual>> VisitForeign_table(context:SQLiteParser.Foreign_tableContext) : Result
    + <<virtual>> VisitIndex_name(context:SQLiteParser.Index_nameContext) : Result
    + <<virtual>> VisitTrigger_name(context:SQLiteParser.Trigger_nameContext) : Result
    + <<virtual>> VisitView_name(context:SQLiteParser.View_nameContext) : Result
    + <<virtual>> VisitModule_name(context:SQLiteParser.Module_nameContext) : Result
    + <<virtual>> VisitPragma_name(context:SQLiteParser.Pragma_nameContext) : Result
    + <<virtual>> VisitSavepoint_name(context:SQLiteParser.Savepoint_nameContext) : Result
    + <<virtual>> VisitTable_alias(context:SQLiteParser.Table_aliasContext) : Result
    + <<virtual>> VisitTransaction_name(context:SQLiteParser.Transaction_nameContext) : Result
    + <<virtual>> VisitWindow_name(context:SQLiteParser.Window_nameContext) : Result
    + <<virtual>> VisitAlias(context:SQLiteParser.AliasContext) : Result
    + <<virtual>> VisitFilename(context:SQLiteParser.FilenameContext) : Result
    + <<virtual>> VisitBase_window_name(context:SQLiteParser.Base_window_nameContext) : Result
    + <<virtual>> VisitSimple_func(context:SQLiteParser.Simple_funcContext) : Result
    + <<virtual>> VisitAggregate_func(context:SQLiteParser.Aggregate_funcContext) : Result
    + <<virtual>> VisitTable_function_name(context:SQLiteParser.Table_function_nameContext) : Result
    + <<virtual>> VisitAny_name(context:SQLiteParser.Any_nameContext) : Result
}
class "AbstractParseTreeVisitor`1"<T> {
}
class "ISQLiteParserVisitor`1"<T> {
}
"AbstractParseTreeVisitor`1" "<Result>" <|-- "SQLiteParserBaseVisitor`1"
"ISQLiteParserVisitor`1" "<Result>" <|-- "SQLiteParserBaseVisitor`1"
@enduml
