version: '3.7'

services:
    frontend:
        build: ./frontend
        ports:
            - 3000:8080
        depends_on:
            - backend
        networks:
            - app-network
    backend:
        build: ./api
        ports:
            - 5000:80
        networks:
            - app-network

networks:
 app-network:
   driver: bridge